name: CI for DatPhong, LoaiDichVu, and HoaDon Tests

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' 


    - name: Restore dependencies
      # DÙNG ĐƯỜNG DẪN LỒNG NHAU ĐÃ XÁC ĐỊNH
      run: dotnet restore Xuong04_QLKS/Xuong04_QLKS/Test_QLKS/Test_QLKS.csproj 


    - name: Build
      run: dotnet build Xuong04_QLKS/Xuong04_QLKS/Test_QLKS/Test_QLKS.csproj --no-restore --configuration Release


    - name: Run Unit Tests (TRX + Coverage) - Your Tests
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path TestResults -Force
       
        dotnet test Xuong04_QLKS/Xuong04_QLKS/Test_QLKS/Test_QLKS.csproj ` 
          --no-build `
          --configuration Release `
          --filter "ClassName~TestDatPhong" `    # CLASS TEST ĐẶT PHÒNG
          --filter "ClassName~LoaiDichVuTests" ` # CLASS TEST LOẠI DỊCH VỤ
          --filter "ClassName~TestHoaDon" `      # CLASS TEST HÓA ĐƠN
          --collect:"XPlat Code Coverage" `
          --logger "trx;LogFileName=Test_QLKS.trx" ` 
          --results-directory "TestResults"
